name: Build and Deploy Specific Version

on:
  workflow_call:
    inputs:
      deploy_confirmation:
        description: 'Outcome if user manually confirmed the start of the deploy script'
        type: string
        required: true
      environment:
        description: 'The environment to build and deploy to'
        required: true
        type: string
      target_version:
        description: 'The version of that needs to be deployed'
        required: true
        type: string
      version_file_path:
        description: The path to the php version file
        type: string
        required: false
        default: app/version.php
      dockerfile:
        description: Relative dockerfile to the docker file seen from the repository root. No leading slash.
        type: string
        required: false
        default: 'deployment/dockerfiles/code/Dockerfile'
      translations_client:
        description: The translation client for which we get the translations, can be 'backend' or 'core'
        type: string
        required: false
      translations_directory:
        description: The directory the translations will be written to for the build to use
        type: string
        required: false
      oauth_enabled:
        description: This build uses oauth authentication and requires the configuration of keys
        type: boolean
        default: false
        required: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: AWS access key id
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: AWS access key secret
      RENTMAN_TRANSLATION_SERVER_SECRET:
        required: false
        description: Secret to access the translation server
      OAUTH_PRIVATE_KEY:
        required: false
        description: The private key for Oauth authentication
      OAUTH_PUBLIC_KEY:
        required: false
        description: The public key for Oauth authentication
      COMPOSER_AUTH:
        required: false
        description: Composer authentication key
      SENTRY_AUTH_TOKEN:
        required: false
        description: The token to authenticate in Sentry

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

jobs:
  ensure-master-branch:
    name: Check current branch
    if: ${{ inputs.deploy_confirmation == 'DEPLOY' || inputs.deploy_confirmation == 'YOLO' }}
    outputs:
      status: ${{ steps.early.outputs.status }}
    runs-on: ubuntu-latest
    steps:
      - id: early
        name: Checking if current branch is master
        run: |
          if [ "${{ github.ref }}" != "refs/heads/master" ]; then
            echo "Error this can only run on master branch"
            exit 1
          fi
          echo "status=success" >> $GITHUB_OUTPUT
  check-environment:
    name: Check if proper environment is passed
    runs-on: ubuntu-latest
    steps:
      - name: Only allow staging and production
        run: |
          if [[ "${{ inputs.environment }}" == "staging" || "${{ inputs.environment }}" == "production" ]]; then
          echo "Running workflow with environment: ${{ inputs.environment }}."
          else
          echo "Invalid environment. Only 'staging' or 'production' are allowed."
          exit 1
          fi
  determine-ecr-image-name:
    name: Determine ecr image name based on environment
    needs: [check-environment, ensure-master-branch]
    outputs:
      image_name: ${{ steps.image_name.outputs.image_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: rentmanpublic/actions
          token: ${{ secrets.GITHUB_TOKEN }}
          path: actions
          ref: master
      - name: Checkout to release repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.github-token.outputs.token || secrets.GITHUB_TOKEN }}
          path: target_repository_folder
          ref: master
      - id: image_name
        name: Check which image name to use based on enviroment
        run: |
          chmod 700 actions/scripts/determine_image_name.sh
          actions/scripts/determine_image_name.sh
        env:
          ENVIRONMENT: ${{ inputs.environment }}

  docker-build:
    name: Build image
    uses: rentmanpublic/actions/.github/workflows/ecr-build-and-push.yml@master
    needs: determine-ecr-image-name
    if: needs.ensure-master-branch.outputs.status == 'success'
    with:
      image_name: ${{ needs.determine-ecr-image-name.outputs.image_name }}
      image_tag: latest ${{ inputs.target_version  }}
      version: ${{ inputs.target_version }}
      dockerfile: ${{ inputs.dockerfile }}
      platforms: amd64
      push_images: 1
      ref: ${{ inputs.target_version }}
      translations_client: ${{ inputs.translations_client }}
      translations_directory: ${{ inputs.translations_directory }}
      oauth_enabled: ${{ inputs.oauth_enabled }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TRANSLATIONS_SECRET: ${{ secrets.RENTMAN_TRANSLATION_SERVER_SECRET }}
      OAUTH_PRIVATE_KEY: ${{ secrets.OAUTH_PRIVATE_KEY }}
      OAUTH_PUBLIC_KEY: ${{ secrets.OAUTH_PUBLIC_KEY }}
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  deploy:
    name: Deploy to ECS
    needs: docker-build
    uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@master
    with:
      environment: ${{ inputs.environment }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
