name: 'Linting'
on:
  - pull_request

jobs:
  lint:
    name: 'Yaml lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Yamllint'
        run: |
          yamllint .
      - name: 'Bash lint'
        run: shellcheck scripts/*
