name: Production Deploy Version

on:
  workflow_call:
    inputs:
      target_version:
        description: 'The version of that needs to be deployed'
        required: true
        type: string
      version_file_path:
        description: The path to the php version file
        type: string
        required: false
        default: app/version.php
      target_repository:
        description: The target repository for the build
        type: string
        required: true
      target_repository_folder:
        description: The folder in which the target repository will be checked out
        type: string
        required: false
        default: target_repository_folder
      image_name:
        description: The name the docker image. This is also the name of the ECR repository
        type: string
        required: true
      dockerfile:
        description: Relative dockerfile to the docker file seen from the repository root. No leading slash.
        type: string
        required: true
      ecs_service:
        description: 'ECS service name'
        type: string
        required: true
      ecs_cluster:
        description: 'ECS cluster name'
        type: string
        required: true
      ecs_region:
        description: 'AWS region'
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: AWS access key id
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: AWS access key secret

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  checkout-release-version:
    name: Checking out the to be released version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: rentmanpublic/actions
          token: ${{ secrets.GITHUB_TOKEN }}
          path: actions
      - name: Checkout to release repo
        uses: actions/checkout@v4
        with:
          ref: 'refs/tags/${{ inputs.target_version }}'
          repository: ${{ inputs.target_repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ inputs.target_repository_folder }}
  docker-build:
    name: Build Production image
    needs: checkout-release-version
    uses: rentmanpublic/actions/.github/workflows/ecr-build-and-push.yml@master
    with:
      image_name: ${{ inputs.image_name }}
      image_tag: latest ${{ inputs.target_version  }}
      dockerfile: ${{ inputs.dockerfile }}
      platforms: amd64
      push_images: 1
      ref: ${{ inputs.target_version }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

  deploy-production:
      name: Deploy to Production
      needs: docker-build
      uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@master
      with:
        service: ${{ inputs.ecs_service }}
        cluster: ${{ inputs.ecs_cluster }}
        region:  ${{ inputs.ecs_region }}
      secrets:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}