name: Production Release Code

on:
  workflow_call:
    inputs:
      version_file_path:
        description: The path to the php version file
        type: string
        required: false
        default: ./app/version.php
      image_name:
        description: The name the docker image. This is also the name of the ECR repository
        type: string
        required: true
      dockerfile:
        description: Relative dockerfile to the docker file seen from the repository root. No leading slahs.
        type: string
        required: true
      ecs_service:
        description: 'ECS service name'
        type: 'string'
        required: true
      ecs_cluster:
        description: 'ECS cluster name'
        type: 'string'
        required: true
      ecs_region:
        description: 'AWS region'
        type: 'string'
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: AWS access key id
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: AWS access key secret

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ensure-master-branch:
    name: Check current branch
    outputs:
      status: ${{ steps.early.outputs.status }}
    runs-on: ubuntu-latest
    steps:
      - id: early
        name: Checking if current branch is master
        run: |
          if [ "${{ github.ref }}" != "refs/heads/master" ]; then
            echo "Error this can only run on master branch"
            exit 1
          fi
          echo "status=success" >> $GITHUB_OUTPUT

  tag:
    name: Generating new GitHub tag
    needs: ensure-master-branch
    if: needs.ensure-master-branch.outputs.status == 'success'
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create new minor version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          default_bump: minor
          dry_run: true

  push-new-tag:
    name: Update version, tagging in GitHub
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push new tag to github
        run: | 
          ./scripts/update_version.sh 
          git config --global user.email "buildbot@rentman.nl"
          git config --global user.name "BuildBot"
          git add ${{ inputs.version_file_path }} 
          git commit -m "Bump version to ${{ needs.tag.outputs.new_tag }}"
          git tag ${{ needs.tag.outputs.new_tag }}
          git push
          git push origin tag ${{ needs.tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_TAG: ${{ needs.tag.outputs.new_tag }}
          VERSION_FILE_PATH: ${{ inputs.version_file_path }}

  docker-build:
    name: Build Production image
    needs: [tag,  push-new-tag]
    uses: ./.github/workflows/ecr-build-and-push.yml
    with:
      image_name: ${{ inputs.image_name }}
      image_tag: latest ${{ needs.tag.outputs.new_tag }}
      dockerfile: ${{ inputs.dockerfile }}
      platforms: amd64
      push_images: 1
      ref: ${{ needs.tag.outputs.new_tag }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

  deploy-production:
      name: Deploy to Production
      needs: docker-build
      uses: ./.github/workflows/ecs-redeploy-service.yml
      with:
        service: ${{ inputs.ecs_service }}
        cluster: ${{ inputs.ecs_cluster }}
        region:  ${{ inputs.ecs_region }}
      secrets:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}