name: Register the start of a QA build
on:
  workflow_call:
    inputs:
      github_action_payload:
         required: true
         description: The github action payload
         type: string
    secrets:
       build_reporting_secret:
         description: The secret used for the toolsendpoint to register QA builds
         required: true
jobs:
  qa-build-register-start:
    runs-on: ubuntu-latest
    steps:
      - name: Register the start of build on the magic machine
        env:
          GITHUB_ACTION_PAYLOAD: ${{inputs.github_action_payload}}
          BUILD_REPORTING_SECRET: ${{secrets.build_reporting_secret}}
        run: |
          echo "$GITHUB_ACTION_PAYLOAD" > payload.json
          jq ".secret=\"${BUILD_REPORTING_SECRET}\"" payload.json > processed.json
          curl -X POST "https://tools.rentman.net/buildreporting.php?rmaction=register" -H 'Content-Type: application/json' --data-binary "@processed.json"
          
