name: Register the stages of a QA build
on:
  workflow_call:
    inputs:
      github_action_payload:
         required: true
         description: The github action payload
         type: string
      stage:
        required: true
        default: building
        type: string
        description: one of [building, built, failed]
    secrets:
       build_reporting_secret:
         description: The secret used for the toolsendpoint to register QA builds
         required: true


jobs:

  qa-build-register-start:

    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.register.outputs.sha }}
    steps:
      - name: Register the stage of the builds
        id: register
        env:
          GITHUB_ACTION_PAYLOAD: ${{inputs.github_action_payload}}
          BUILD_REPORTING_SECRET: ${{secrets.build_reporting_secret}}
          STAGE: ${{inputs.stage}}
        run: |
          if [[ "$STAGE" != @(building|built|failed) ]]; then
            echo "Invalid build stage"
            exit 1
          fi
          echo "$GITHUB_ACTION_PAYLOAD" > payload.json
          jq ".secret=\"${BUILD_REPORTING_SECRET}\"" payload.json > processed.json
          curl -X POST "https://tools.rentman.net/buildreporting.php?rmaction=$STAGE" -H 'Content-Type: application/json' --data-binary "@processed.json"
          event_type="$(jq -r '.event_name' processed.json)"
          if [ "$event_type" = "pull_request" ]; then
             sha="$(jq -r '.event.pull_request.head.sha' processed.json)"
          else
             sha="$(jq -r '.sha' processed.json)"
          fi
          echo "Storing SHA as output: ${sha}"
          echo "::set-output name=sha::$(echo $sha)"
        
