name: Redeploy Latest Version in AWS without Building

on:
  workflow_call:
    inputs:
      deploy_confirmation:
        description: 'Outcome if user manually confirmed the start of the deploy script'
        type: string
        required: true
      environment:
        description: 'The environment to build and deploy to'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: AWS access key id
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: AWS access key secret

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

jobs:
  check-environment:
    name: Check if proper environment is passed
    runs-on: ubuntu-latest
    steps:
      - name: Only allow staging and production
        run: |
          if [[ "${{ inputs.environment }}" == "staging" || "${{ inputs.environment }}" == "production" ]]; then
          echo "Running workflow with environment: ${{ inputs.environment }}."
          else
          echo "Invalid environment. Only 'staging' or 'production' are allowed."
          exit 1
          fi
  deploy:
    name: Redeploy latest image available on ECR to ECS
    needs: check-environment
    if: ${{ inputs.deploy_confirmation == 'DEPLOY' || inputs.deploy_confirmation == 'YOLO' }}
    uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@master
    with:
      environment: ${{ inputs.environment }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
